export const FP5_SEED = {
		  mayfung: {icon:'ic-teacup', title:'May Fung amid Meshes of The Afternoon',
		    meta:'<b>2026.10.17</b> · Fountain Teatime 開幕場 · 日期已確定',
		    tags:['社群連結','標誌系列','講座'],
		    desc:'馮美華借 Maya Deren 嘅實驗短片《Meshes of the Afternoon》做參照，回望自己一路行過嚟嘅生活同存在方式 — 有時真實、有時超現實嘅一連串夢，交纏成一個以實驗精神為軸嘅存在。佢會放自己第一條短片《The Sea》（super 8，4 分鐘，數碼檔播放）打開話題。',
		    pics:['MF','L']},
		  halloween1: {icon:'ic-disc', title:'《活死人黎明 Dawn of the Dead》',
		    meta:'<b>2026.10.30（6:30–9:30pm）</b> · Halloween Apocalypse 萬聖末日啟示 · Laser Frames 第一輯 · 日期已確定',
		    tags:['有收入','社群連結','放映','媒體考古'],
		    desc:['George A. Romero 1978 年嘅《活死人黎明 Dawn of the Dead》。Hector 從佢嘅 laserdisc 收藏揀恐怖片，以 private cine club 形式放映，需要預先登記。',
		      '三晚系列嘅第一晚，共同問題：我哋有幾人類？ How human are we? 每場都有導讀、分析同討論。',
		      '技術上跟足 D1 規格 — 用分配放大器推幾部 CRT，唔用被動分線，保住每部電視都收到足電壓嘅訊號。'],
		    pics:['H']},
		  halloween2: {icon:'ic-disc', title:'《變形邪魔 Invasion of the Body Snatchers》兩版連放',
		    meta:'<b>2026.10.31（5:00–9:00pm）</b> · Halloween Apocalypse 萬聖末日啟示 · LaserFrames 第一輯 · 日期已確定',
		    tags:['有收入','社群連結','放映','媒體考古'],
		    desc:['1956 年（Don Siegel）同 1978 年（Philip Kaufman）兩個版本連放，一次過對照兩個年代點樣講同一個恐懼。',
		      '三晚系列嘅第二晚，共同問題：我哋有幾人類？ How human are we? 每場都有導讀、分析同討論。',
		      'Private cine club 形式，需要預先登記。技術上跟足 D1 規格 — 用分配放大器推幾部 CRT，唔用被動分線。'],
		    pics:['H']},
		  halloween3: {icon:'ic-disc', title:'《復製嬌妻 The Stepford Wives》',
		    meta:'<b>2026.11.07（5:00–9:00pm）</b> · Halloween Apocalypse 萬聖末日啟示 · Laser Frames 第一輯 · 日期已確定',
		    tags:['有收入','社群連結','放映','媒體考古'],
		    desc:['Bryan Forbes 1975 年嘅《復製嬌妻 The Stepford Wives》，三晚系列嘅收官一場。',
		      '共同問題：我哋有幾人類？ How human are we? 每場都有導讀、分析同討論。',
		      'Private cine club 形式，需要預先登記。技術上跟足 D1 規格 — 用分配放大器推幾部 CRT，唔用被動分線。'],
		    pics:['H']},
		  xmasghost: {icon:'ic-disc', title:'Christmas Ghosts · 《The Legend of Hell House》',
		    meta:'<b>2026.12.26（5:00–9:00pm）</b> · LaserFrames · OPEN TO ALL · 日期已確定',
		    tags:['社群連結','放映','媒體考古'],
		    desc:['John Hough 1973 年嘅《The Legend of Hell House》（93 分鐘），gothic supernatural horror，來自 Hector 嘅 laserdisc 收藏。',
		      '公開場，唔使 cine-club 會籍。CRT 同步播映，跟足 D1 規格。More details to come.'],
		    pics:['H']},
		  widescreen: {icon:'ic-crt', title:'Widescreen cinema and the nature of the frame 寬銀幕電影與畫框的性質',
		    meta:'<b>2026.12.05（Sat 3:00–5:30pm）</b> · LaserFrames · 日期已確定',
		    tags:['社群連結','講座','媒體考古'],
		    desc:['There is no true version of a film. Every frame is a matrix of possibilities. Learn about the “soft matte” and “open matte” approach.',
		      'Hector Rodriguez 主講：寬銀幕電影同畫框嘅性質。'],
		    pics:['H']},
		  halloween2027: {icon:'ic-disc', title:'Halloween Apocalypse 2027',
		    meta:'<b>2027.10.30–31</b>（Sat–Sun）· LaserFrames Cine Club · 日期待確認',
		    tags:['有收入','社群連結','放映','媒體考古'],
		    desc:['Halloween Apocalypse 第二年：LaserFrames 再來萬聖放映（2027.10.30–31 Saturday to Sunday）。確實片單仍待確認。',
		      'Private cine club 形式，需要預先登記。CRT 同步播映，跟足 D1 規格。'],
		    pics:['H']},
		  teatime: {icon:'ic-teacup', title:'Fountain Teatime 噴泉茶聚',
		    meta:'循環系列 · 雙月一次 · 2026–2029 持續',
		    tags:['社群連結','標誌系列','實驗性'],
		    desc:['請唔同嘉賓嚟傾 being、living、doing、survival 同 interdisciplinarity。FP 策劃，Linda Lai 統籌，雙月一次。',
		      '已確定場次：<b>2026.10.17</b> May Fung《May Fung amid Meshes of The Afternoon》；<b>2026.12.12</b> Jen Lee《Being, Experiencing, Perceiving, and Knowing in the More-Than-Human World》。',
		      '排期中：Lau Ho-chi 講展覽製作作為職業（2027，日期待定）；2027 尾或 2028 有《Name of the Will》遊戲開發者分享、Hugo Yeung 嘅項目，潛在合作者 Zeitgeist Studio（Mandy Wong 同 Jerry Chan）。'],
		    pics:['L','MF','JL']},
		  teatime2: {icon:'ic-teacup', title:'Being, Experiencing, Perceiving, and Knowing in the More-Than-Human World',
		    meta:'<b>2026.12.12</b>（3–6pm）· Fountain Teatime 第二場 · 日期已確定',
		    tags:['社群連結','標誌系列','講座'],
		    desc:'策展人、博士後研究員 Jen Lee 主講：喺一個「超越人類」嘅世界裡面，存在、經驗、感知同認知各自意味著咩。接住 10 月 May Fung 場，係噴泉茶聚第二場。',
		    pics:['JL','L']},
		  cineclub: {icon:'ic-crt', title:'LaserFrames Cine Club · 雷射視盤',
		    meta:'Clubs & Series · 循環系列 · 2026–2029 · 4 節 × 2 輯 · 需預先登記',
		    tags:['有收入','社群連結','實驗性','媒體考古'],
		    desc:['把賽璐珞電影轉上 laserdisc 唔止係保存一份拷貝。Laserdisc 唔同 VHS、VCD、DVD、Blu-ray 呢啲替代技術版本 — 佢係類比媒體，畫幀以連續流嘅方式存在，唔經數碼轉換。佢係一套獨特嘅儲存系統，而佢嘅消費者版本保留咗比 DVD 同其他數碼媒體更多關於電影製作嘅事實。',
		      '呢個以技術為本嘅系列會配合劇情長片放映（2006 年或之前）做現場導讀同討論 — 一邊睇舊片，一邊聽平時少有人講嘅製作真相。系列由「Halloween Apocalypse 2026」打頭陣；12 月有寬銀幕講座同公開場 Christmas Ghosts；2027 年再有 Halloween Apocalypse。可以按季（2026.10–2027.01）加入，或逐場參加。',
		      '放映形式唔係戲院式：三至四部舊 CRT 電視散落空間，同步播同一畫面，觀眾喺唔同角落各自圍住細電視睇 — 親密、可以傾偈、似裝置多過似戲院。以會員制 cine-club 結構運作（法律細節仍需本地確認）。'],
		    links:['halloween1','halloween2','halloween3','widescreen','xmasghost','halloween2027'],
		    pics:['H']},
		  adminnight: {icon:'ic-laptop', title:'FP Open!「打開門」做吓事務局',
		    meta:'循環系列 · 每月 2–3 日 · <b>2026.10.02–04</b> 試局（2–8pm）',
		    tags:['社群連結','工作空間','自由定價'],
		    desc:['Admin night、chore settlement、面對面 hang out — 把非創作嘅事務（覆 email、申請 grant、整檔案）同創作活動接駁埋一齊。',
		      'Andio、Fuk-kuen 同 Sing 喺 FP 做嘢，公眾可以一齊上嚟做自己積落嘅嘢，中間夾雜小型分享。基調安靜，似自修室。歡迎 donation。',
		      '#工作空間 #學習 #閒聊 #自由定價'],
		    pics:['A','FK','S']},
		  spatial: {icon:'ic-speaker', title:'Spatial Calibration 空間校正',
		    meta:'循環系列 · 每季一次 · 2026–2029 · 聲音表演',
		    tags:['社群連結','實驗性','有收入'],
		    desc:'名字嚟自以前喺工廠大廈唔可以做公開演出，於是叫「聲壓測試」。重點係提供一個試煉場，俾經驗未夠嘅 sound artist 落場表演 — FP 負責場地、觀眾、海報設計同宣傳。',
		    pics:['A']},
		  workshop: {icon:'ic-chip', title:'Device-making Workshop Series',
		    meta:'循環系列 · 2026–2029 · 兩條軌道 · 日期待定',
		    tags:['有收入','實驗性','社群連結'],
		    desc:'兩條線：Andio 嘅 device-making，暫定四節系列（仍待佢確認），教藝術家落手做硬件；Fuk-kuen 嘅藝術家個人網站工作坊 — 仲月月俾錢 WIX？用 AI 自己起一個，一日內或最多連續兩日搞掂。呢條線係最直接嘅收入來源。',
		    pics:['A','FK']},
		  modular: {icon:'ic-knobs', title:'Synth / DAW / Modular 玩聲角',
		    meta:'Play room + Artefact Corner · 半年一次 · 2026–2029',
		    tags:['實驗性','有收入'],
		    desc:'唔算係一個活動 — 係一個 play room：FP 擺出器材（FK 會帶埋自己嘅 modular），俾人上嚟玩聲、錄聲。現場租器材同 donation 做收入。可以同 artefact corner 合埋一齊做。',
		    pics:['A','FK']},
		  mediaarch: {icon:'ic-cassette', title:'Club-MA 媒體考古 Club Media Archaeology',
		    meta:'Clubs & Series · 研究線 · 總覽 · 貫穿 2026–2029',
		    tags:['實驗性','標誌系列','媒體考古','Club-MA'],
		    desc:['Linda Lai 主持嘅 Club Media Archaeology（Club-MA）— Linda 學術書寫嘅延伸，唔係一個單一活動，而係一條貫穿全期嘅研究線，圍住「舊媒體、舊格式點樣喺當下仲有生命力」呢個大問題轉。',
		      'Club-MA 分三個 phase：01 榕樹下（四節，2026.11.21、11.28、2027.01.30、02.06）→ 02 除草接枝施肥（研究工作坊）→ 03 Archive Unheard 奇異叢林（2028.03 在地爆發展覽）。每 phase 有 3–4 次、每次 3 小時嘅聚會；成員可以揀參加一個、兩個或全部 phase。',
		      '另外仲有一個 <b>pop-up 展覽</b>（免費入場）：用返 Linda 自己舊作嘅材料重新編排展出，唔係新製作，係舊素材嘅新讀法 — 日期未定。',
		      '呢條線同 Hector 嘅 LaserFrames Cine Club / laserdisc 線，同埋 Angela Su 嘅香港媒體藝術調查出版計劃互相呼應扣連。'],
		    links:['mediaarch1a','mediaarch1b','mediaarch1c','mediaarch1d','mediaarch2','mediaarch3'],
		    pics:['L','H']},
		  stc: {icon:'ic-shuffle', title:'Subject to Change',
		    meta:'流動 · 未定形',
		    tags:['實驗性'],
		    desc:'Ho-chi 嘅開放式新計劃：由 "subject"、"to"、"change" 三個字嘅重新排列衍生活動。刻意保持流動、未定形 — 所以喺呢張地圖上只標到節奏，標唔到內容。',
		    pics:['HC']},
		  ml: {icon:'ic-net', title:'Poetics of ML Series 學習系統的詩學',
		    meta:'FP5.0 標誌性總結系列 · 2028–2029 · 12 週課程 · 待 ADC 批款（申請 2026.12 交）',
		    tags:['有收入','社群連結','標誌系列'],
		    desc:['兩條平行軌道：Track 1「基礎編程」（4週）打底，由零開始學 Python 同基本邏輯；Track 2「ML實作」（4週）進階到用 scikit-learn 同 PyTorch 訓練同操作實際模型。每節3小時，每軌大約24小時，用 Google Colab 做教學平台，上限30人，務求人人有機會落手做，唔係得個睇字。',
		      'Hector 係主教，貫穿成個課程嘅技術脈絡；但呢個唔止係一個 coding class — 前面有 Linda 嘅「影像作為數據」講座打頭陣，由非技術角度切入，講點樣睇「一張圖」變成「一堆數字」呢件事本身有咩文化含義，同埋帶學員做城市考察，將呢種思考帶出課室。課程中段有 Winnie Soon 同 Fiona Lau 嘅 lecture-performance「Generating dialogue, generating text」，用表演形式拆解人機對話同文本生成呢個題目。尾聲收喺 Hector 嘅公開講座「Poetics of Infrastructure」，將前面成套技術訓練拉返上去，問返「基礎建設本身有冇詩意」呢個大問題。',
		      '即係話成套嘢嘅骨架係編程訓練，但血肉係文化提問 — 技術同人文兩條線一齊教，先夠得上「學習系統的詩學」呢個名。（延伸版本預算約 HK$192,060，含10%行政費；12月前要交 ADC 申請。）'],
		    pics:['H','HG','L']},
		  vcd: {icon:'ic-film', title:'More than Found Footage 何止現成影音碎片咁簡單',
		    meta:'公開徵集 · 2027.04 開 → 2027.10 截 → 2028.03 發表',
		    tags:['社群連結','標誌系列','公開徵集'],
		    desc:['大約 300 套香港商業電影嘅 VCD 會開放俾申請者（按公佈名單揀）複製做再創作。同 Wai 嘅 VCD shop 同 zine 系列「Wanna watch again」係同一條線。',
		      '<ul><li><b>2027.04–10</b>：導論講座；四月開徵集，十月截止</li>'
		      +'<li><b>2027.11 – 2028.02</b>：評審選拔同宣傳</li>'
		      +'<li><b>2028.03</b>：發表 — 放映會加討論</li></ul>',
		      '合作單位待定。'],
		    pics:['L','W']},
		  fkinstall: {icon:'ic-motion', title:'Motion Gesture Tracking 動作追蹤聲音裝置',
		    meta:'一次性展覽 · 2027.09–10（待確認）· 展期 3–4 週',
		    tags:['實驗性'],
		    desc:'Motion gesture tracking 聲音裝置，可以同 modular 一齊展出。一次性展覽，大約一年之後先發生 — 確實日期未定，所以喺呢度只虛指住 2027 呢條地平線。',
		    pics:['FK']},
		  crtwall: {icon:'ic-wall', title:'CRT Wall 盒裝故事',
		    meta:'一次性展覽 · 2027 或 2028（待確認）· 展期 3–4 週',
		    tags:['實驗性','社群連結'],
		    desc:'Sing 嘅流動影像 CRT 牆，帶參與式成分，FP 提供場地同 CRT。排期要留意：同 Private Cine Club 用緊同一批電視機 — 展覽霸機嗰段時間，放映要停或改單一投影。',
		    pics:['S']},
		  board: {icon:'ic-board', title:'地形康樂棋 Topographic Carrom',
		    meta:'Play room · 一次性 · 2027 · 製作＋開玩',
		    tags:['社群連結','實驗性'],
		    desc:'自己鬥木整嘅康樂棋：棋盤唔係普通正方形 — 上面有山、草地、障礙物；唔止四個窿，中間仲有好多窿；另加特別規則，例如用三隻棋圍住對手中間會死。由 Ng Sing 同 Fuk-kuen 認頭做 lead。',
		    pics:['S','FK']},
		  toy: {icon:'ic-robot', title:'Toy as Medium #4',
		    meta:'一次性展覽 · 約 2028',
		    tags:['標誌系列','社群連結','有收入'],
		    desc:'FP 招牌研究型項目，2016–2023 已做三輯。第四輯強調跨學科同媒體考古視角 — 觀眾可以用手觸碰物件嘅玩具機器展，由硬件工作坊長出嚟。',
		    pics:['A']},
		  mediaarch1a: {icon:'ic-cassette', title:'Club-MA 01 · 媒體考古…榕樹下（第一節）',
		    meta:'<b>2026.11.21（3–6pm）</b> · Club-MA Phase 1 · 四節之一 · 日期已確定',
		    tags:['實驗性','標誌系列','講座','媒體考古'],
		    desc:['Club-MA Phase 1 開課，講座加工作坊，一共四節，由 Linda Lai 主持。',
		      '前人的日常「欲望」驅策着「新」媒體同工具嘅出現，即使佢哋仲未有名。呢一輯就係由呢個問題行開去。',
		      '<ul><li>媒體考古個案逐個講：遠程臨場、永生不朽、光與火、指頭的故事、記憶同庫存…</li>'
		      +'<li>媒體考古點樣豐富我哋對媒體（藝術）實踐嘅理解 — 由研究嘅視野走到藝術創作嘅視野。</li></ul>'],
		    pics:['L']},
		  mediaarch1b: {icon:'ic-cassette', title:'Club-MA 01 · 媒體考古…榕樹下（第二節）',
		    meta:'<b>2026.11.28（3–6pm）</b> · Club-MA Phase 1 · 四節之二 · 日期已確定',
		    tags:['實驗性','標誌系列','講座','媒體考古','Club-MA'],
		    desc:['Club-MA Phase 1 第二節，講座加工作坊，由 Linda Lai 主持。',
		      '延續日常生活中嘅媒體考古片段同時刻：遠程臨場、永生不朽、光與火、指頭的故事、記憶同庫存…'],
		    pics:['L']},
		  mediaarch1c: {icon:'ic-cassette', title:'Club-MA 01 · 媒體考古…榕樹下（第三節）',
		    meta:'<b>2027.01.30（3–6pm）</b> · Club-MA Phase 1 · 四節之三 · 日期已確定',
		    tags:['實驗性','標誌系列','講座','媒體考古','Club-MA'],
		    desc:['Club-MA Phase 1 第三節，講座加工作坊，由 Linda Lai 主持。',
		      '由研究嘅視野行向藝術創作嘅視野：媒體考古點樣改寫我哋對媒體（藝術）實踐嘅理解。'],
		    pics:['L']},
		  mediaarch1d: {icon:'ic-cassette', title:'Club-MA 01 · 媒體考古…榕樹下（第四節）',
		    meta:'<b>2027.02.06（3–6pm）</b> · Club-MA Phase 1 · 四節之四 · 日期已確定',
		    tags:['實驗性','標誌系列','講座','媒體考古','Club-MA'],
		    desc:['Club-MA Phase 1 嘅收結一節，講座加工作坊，由 Linda Lai 主持。',
		      '收攏四節嘅個案同討論，為 Phase 2「除草接枝施肥」嘅展覽製作工作坊鋪路。'],
		    pics:['L']},
		  mediaarch2: {icon:'ic-plant', title:'Club-MA 02 · 媒體考古…除草接枝施肥',
		    meta:'2027–2028 · Club-MA Phase 2 · 3 節 × 3 小時 · 日期待定',
		    tags:['實驗性','標誌系列','工作坊','媒體考古','Club-MA'],
		    desc:['Club-MA Phase 2 轉入展覽製作（exhibition-making），三節工作坊：',
		      '<ul><li><b>工作坊 (1)</b>：建構影像圖譜 — 由日常物品構成嘅想像樹狀網絡。</li>'
		      +'<li><b>工作坊 (2)</b>：追尋驅動工具發明嘅「慾望」，由呢個角度重新理解科技史。</li>'
		      +'<li><b>工作坊 (3)</b>：追溯個人嘅藝術／創作脈絡 — 整理成一份屬於自己嘅作品係譜。</li></ul>'],
		    pics:['L']},
		  mediaarch3: {icon:'ic-tree', title:'Club-MA 03 · Archive Unheard 媒體考古…奇異叢林',
		    meta:'<b>2028.03</b> · Club-MA Phase 3 · 在地爆發展覽 · 月份已確定',
		    tags:['實驗性','標誌系列','展覽','媒體考古','Club-MA'],
		    desc:'Archive Unheard, on-site group exhibition。把 Club-MA 1–2 嘅講座／工作坊所獲化為在地爆發展覽，同參加者合作。',
		    pics:['L']},
		  jazz: {icon:'ic-note', title:'Jazz vs Experimental Sound',
		    meta:'2027 或 2028（待確認）· 三個演出單元',
		    tags:['實驗性','社群連結','表演'],
		    desc:'爵士同實驗聲音嘅演出。目標三個演出單元，其中一個會以製作一份 FP Manual 為目標。Sing 正邀請「Fountain de Chopin 翻騰三周半」同其他爵士樂愛好者做潛在合作者。日期未定。',
		    pics:['S']},
		  mnemonic: {icon:'ic-chip', title:'mnemonic catastrophe',
		    meta:'2027 或 2028（待確認）· 個人展覽',
		    tags:['實驗性','數據文化'],
		    desc:'Hugo Yeung 嘅展覽，回應當下機器學習生態裡面由數據文化衍生出嚟嘅問題。確實日期待定。',
		    pics:['HG']},
		  essaying: {icon:'ic-mic', title:'Essaying with Sight and Sound 聲影散文探索：講演式表演系列',
		    meta:'公開徵集 · 2028.04 開 → 2028.06 截 → 2029.03 發表',
		    tags:['社群連結','公開徵集','表演'],
		    desc:['公開徵集提案加導論講座，申請要交：題目、論點、媒介範圍、素材來源、演出流程（大綱）。',
		      '<ul><li><b>2028.04–06</b>：四月開徵集，六月截止收提案</li>'
		      +'<li><b>2028.07 – 2029.11</b>：評審選拔同行政安排</li>'
		      +'<li><b>2029.03</b>：發表 — 開門講演式表演系列</li></ul>',
		      '合作單位待定。'],
		    pics:['L']},
		  platform: {icon:'ic-shop', title:'FLOATING PLATFORM 據㸃浮台',
		    meta:'常設 · 2026–2029 · JCCAC L3-06D',
		    tags:['有收入','社群連結','常設'],
		    desc:'FP 喺 JCCAC L3-06D 嘅寄賣角（sales corner），全期常設。由 Lai Wai-leung 負責。',
		    pics:['W']},
		  tsundoku: {icon:'ic-books', title:'Tsundoku 負載讀取',
		    meta:'一次性 · 開放周末 · <b>2029.04</b>（待確認）',
		    tags:['社群連結'],
		    desc:'「積書」：一座書山堆喺 FP 空間度。開放周末做現場裝置；再嚟嘅周末做再創造 — 分類、堆山丘、另類閱讀方法、造新書。可以做 JCCAC 合作項目。',
		    pics:['L','FP']}
		};
